In [1]:
%pip install transformers torch pandas openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting transformers
  Downloading transformers-4.57.6-py3-none-any.whl (12.0 MB)
     |████████████████████████████████| 12.0 MB 11.8 MB/s eta 0:00:01
Collecting torch
  Downloading torch-2.2.2-cp39-none-macosx_10_9_x86_64.whl (150.8 MB)
     |████████████████████████████████| 150.8 MB 1.1 MB/s eta 0:00:01    |█▋                              | 7.4 MB 46.1 MB/s eta 0:00:04
Requirement already satisfied: pandas in /Users/nadia/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: openpyxl in /Users/nadia/Library/Python/3.9/lib/python/site-packages (3.1.5)
Collecting requests
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 6.5 MB/s  eta 0:00:01
Requirement already satisfied: tqdm>=4.27 in /Users/nadia/Library/Python/3.9/lib/python/site-packages (from transformers) (4.67.3)
Requirement already satisfied: numpy>=1.17 in /Users/nadia/Library/Python/3.9/lib/python/site-packages (from transformers) (2.0.2)
Collecting safetensors>=0.4.3
  Downloading safetensors-0.7.0-cp38-abi3-macosx_10_12_x86_64.whl (467 kB)
     |████████████████████████████████| 467 kB 13.0 MB/s eta 0:00:01
Requirement already satisfied: packaging>=20.0 in /Users/nadia/Library/Python/3.9/lib/python/site-packages (from transformers) (26.2)
Collecting filelock
  Downloading filelock-3.19.1-py3-none-any.whl (15 kB)
Collecting pyyaml>=5.1
  Downloading pyyaml-6.0.3-cp39-cp39-macosx_10_13_x86_64.whl (184 kB)
     |████████████████████████████████| 184 kB 8.2 MB/s eta 0:00:01
Collecting regex!=2019.12.17
  Downloading regex-2026.1.15-cp39-cp39-macosx_10_9_x86_64.whl (290 kB)
     |████████████████████████████████| 290 kB 12.5 MB/s eta 0:00:01
Collecting huggingface-hub<1.0,>=0.34.0
  Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
     |████████████████████████████████| 566 kB 27.2 MB/s eta 0:00:01
Collecting tokenizers<=0.23.0,>=0.22.0
  Downloading tokenizers-0.22.2-cp39-abi3-macosx_10_12_x86_64.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 45.5 MB/s eta 0:00:01
Collecting jinja2
  Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
     |████████████████████████████████| 134 kB 14.4 MB/s eta 0:00:01
Collecting networkx
  Downloading networkx-3.2.1-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 86.3 MB/s eta 0:00:01
Collecting fsspec
  Downloading fsspec-2025.10.0-py3-none-any.whl (200 kB)
     |████████████████████████████████| 200 kB 75.1 MB/s eta 0:00:01
Requirement already satisfied: typing-extensions>=4.8.0 in /Users/nadia/Library/Python/3.9/lib/python/site-packages (from torch) (4.15.0)
Collecting sympy
  Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
     |████████████████████████████████| 6.3 MB 14.8 MB/s eta 0:00:01
Requirement already satisfied: tzdata>=2022.7 in /Users/nadia/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/nadia/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/nadia/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: et-xmlfile in /Users/nadia/Library/Python/3.9/lib/python/site-packages (from openpyxl) (2.0.0)
Collecting hf-xet<2.0.0,>=1.1.3
  Downloading hf_xet-1.5.0-cp37-abi3-macosx_10_12_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 12.3 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Collecting MarkupSafe>=2.0
  Downloading markupsafe-3.0.3-cp39-cp39-macosx_10_9_x86_64.whl (11 kB)
Requirement already satisfied: idna<4,>=2.5 in /Users/nadia/Library/Python/3.9/lib/python/site-packages (from requests->transformers) (3.15)
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 7.4 MB/s eta 0:00:01
Requirement already satisfied: certifi>=2017.4.17 in /Users/nadia/Library/Python/3.9/lib/python/site-packages (from requests->transformers) (2026.4.22)
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.7-cp39-cp39-macosx_10_9_universal2.whl (299 kB)
     |████████████████████████████████| 299 kB 11.0 MB/s eta 0:00:01
Collecting mpmath<1.4,>=1.1.0
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
     |████████████████████████████████| 536 kB 13.6 MB/s eta 0:00:01
Installing collected packages: urllib3, charset-normalizer, requests, pyyaml, hf-xet, fsspec, filelock, mpmath, MarkupSafe, huggingface-hub, tokenizers, sympy, safetensors, regex, networkx, jinja2, transformers, torch
Successfully installed MarkupSafe-3.0.3 charset-normalizer-3.4.7 filelock-3.19.1 fsspec-2025.10.0 hf-xet-1.5.0 huggingface-hub-0.36.2 jinja2-3.1.6 mpmath-1.3.0 networkx-3.2.1 pyyaml-6.0.3 regex-2026.1.15 requests-2.32.5 safetensors-0.7.0 sympy-1.14.0 tokenizers-0.22.2 torch-2.2.2 transformers-4.57.6 urllib3-2.6.3
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
from transformers import pipeline

print("Pakete funktionieren.")

/Users/nadia/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/nadia/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/IPython/core/interactiveshell.py", line 3048, in run_cell
    result = self._run_cell(
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/IPython/core/interactiveshell.py", line 3103, in _run_cell
    result = runner(coro)
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/IPython/core/interactiveshell.py", line 3308, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/IPython/core/interactiveshell.py", line 3490, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/34/5hks_4n95h93mnb98rc369v00000gn/T/ipykernel_2199/840675025.py", line 2, in <module>
    from transformers import pipeline
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/transformers/__init__.py", line 27, in <module>
    from . import dependency_versions_check
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/transformers/utils/__init__.py", line 24, in <module>
    from .auto_docstring import (
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/transformers/utils/auto_docstring.py", line 30, in <module>
    from .generic import ModelOutput
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/transformers/utils/generic.py", line 51, in <module>
    import torch
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/nadia/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/nadia/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),

Pakete funktionieren.

In [2]:
%pip install "numpy<2"

Defaulting to user installation because normal site-packages is not writeable
Collecting numpy<2
  Downloading numpy-1.26.4-cp39-cp39-macosx_10_9_x86_64.whl (20.6 MB)
     |████████████████████████████████| 20.6 MB 8.0 MB/s eta 0:00:01     |█████████████████████████████   | 18.7 MB 8.0 MB/s eta 0:00:01
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
Successfully installed numpy-1.26.4
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
from transformers import pipeline

print("Pakete funktionieren.")

/Users/nadia/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/nadia/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Pakete funktionieren.

In [1]:
import pandas as pd

reviews = pd.read_excel("reviews_neu.xlsx")
listings = pd.read_csv("listings_clean.csv")

print("Reviews-Datei:")
print(reviews.shape)
print(reviews.columns.tolist())

print("\nListings-Datei:")
print(listings.shape)
print(listings.columns.tolist())

Reviews-Datei:
(635471, 2)
['listing_id', 'date']

Listings-Datei:
(6054, 24)
['id', 'listing_url', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'property_type', 'room_type', 'accommodates', 'price', 'minimum_nights', 'availability_365', 'number_of_reviews', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'instant_bookable', 'calculated_host_listings_count', 'reviews_per_month', 'price_per_guest', 'price_to_neighborhood_ratio', 'log_reviews_per_month']

In [2]:
import pandas as pd

reviews_text = pd.read_csv("reviews.csv.gz", compression="gzip")

print("Reviews-Text-Datei:")
print(reviews_text.shape)
print(reviews_text.columns.tolist())

reviews_text.head()

Reviews-Text-Datei:
(635471, 6)
['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments']

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,3176,4283,2009-06-20,21475,Milind,"excellent stay, i would highly recommend it. a..."
1,3176,134722,2010-11-07,263467,George,Britta's apartment in Berlin is in a great are...
2,3176,144064,2010-11-24,76726,Patricia,"Fantastic, large place in good location. Only ..."
3,3176,156702,2010-12-21,291657,Benedetta,L'appartamento di Britta è molto largo carino ...
4,3176,165048,2011-01-04,279789,Aude,We went in Berlin for the new year eve. The ap...

In [3]:
# Listings-Datei laden
listings = pd.read_csv("listings_clean.csv")

# Review-Texte mit den Listing-Bewertungen verbinden
df = reviews_text.merge(
    listings[["id", "review_scores_rating"]],
    left_on="listing_id",
    right_on="id",
    how="left"
)

print(df.shape)
df.head()

(635471, 8)

,listing_id,id_x,date,reviewer_id,reviewer_name,comments,id_y,review_scores_rating
0,3176,4283,2009-06-20,21475,Milind,"excellent stay, i would highly recommend it. a...",3176.0,4.63
1,3176,134722,2010-11-07,263467,George,Britta's apartment in Berlin is in a great are...,3176.0,4.63
2,3176,144064,2010-11-24,76726,Patricia,"Fantastic, large place in good location. Only ...",3176.0,4.63
3,3176,156702,2010-12-21,291657,Benedetta,L'appartamento di Britta è molto largo carino ...,3176.0,4.63
4,3176,165048,2011-01-04,279789,Aude,We went in Berlin for the new year eve. The ap...,3176.0,4.63

In [9]:
# Bereinigung der Daten

#  Zeilen ohne Kommentar oder ohne Rating entfernen
df = df.dropna(subset=["comments", "review_scores_rating"])

# Kommentare als Text behandeln
df["comments"] = df["comments"].astype(str)

# Sehr kurze Kommentare entfernen
df = df[df["comments"].str.len() > 10]

print(df.shape)

df[["listing_id", "comments", "review_scores_rating"]].head(10)

(518462, 9)

,listing_id,comments,review_scores_rating
0,3176,"excellent stay, i would highly recommend it. a...",4.63
1,3176,Britta's apartment in Berlin is in a great are...,4.63
2,3176,"Fantastic, large place in good location. Only ...",4.63
3,3176,L'appartamento di Britta è molto largo carino ...,4.63
4,3176,We went in Berlin for the new year eve. The ap...,4.63
5,3176,"Location, location, location! Britta's place w...",4.63
6,3176,We were there to find out what life is like in...,4.63
7,3176,"Recommended! Nice, informative and easy to dea...",4.63
8,3176,Britta's flat is very nice and in a wonderful ...,4.63
9,3176,Britta's flat was perfect for our week end in ...,4.63

In [17]:
# Erstellen eines Testdatensatzes mit 100 Reviews
df_test = df.head(100).copy()

print(df_test.shape)

df_test[["listing_id", "comments", "review_scores_rating"]].head(10)

(100, 9)

,listing_id,comments,review_scores_rating
0,3176,"excellent stay, i would highly recommend it. a...",4.63
1,3176,Britta's apartment in Berlin is in a great are...,4.63
2,3176,"Fantastic, large place in good location. Only ...",4.63
3,3176,L'appartamento di Britta è molto largo carino ...,4.63
4,3176,We went in Berlin for the new year eve. The ap...,4.63
5,3176,"Location, location, location! Britta's place w...",4.63
6,3176,We were there to find out what life is like in...,4.63
7,3176,"Recommended! Nice, informative and easy to dea...",4.63
8,3176,Britta's flat is very nice and in a wonderful ...,4.63
9,3176,Britta's flat was perfect for our week end in ...,4.63

In [18]:
# Laden des Modells
from transformers import pipeline

sentiment_model = pipeline(
    "sentiment-analysis",
    model="nlptown/bert-base-multilingual-uncased-sentiment"
)

print("Modell geladen.")

/Users/nadia/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/nadia/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Device set to use mps:0

Modell geladen.

In [19]:
# Modell testen
test_texts = [
    "Excellent stay, I would highly recommend it.",
    "The apartment was okay, but a bit noisy.",
    "The room was dirty and the host was unfriendly."
]

for text in test_texts:
    result = sentiment_model(text)[0]
    print(text)
    print(result)
    print()

Excellent stay, I would highly recommend it.
{'label': '5 stars', 'score': 0.8754795789718628}

The apartment was okay, but a bit noisy.
{'label': '3 stars', 'score': 0.824542224407196}

The room was dirty and the host was unfriendly.
{'label': '1 star', 'score': 0.5863538980484009}

In [20]:
# Funktion bauen
def predict_sentiment_stars(text):
    result = sentiment_model(str(text)[:512])[0]
    label = result["label"]  # z.B. "5 stars" oder "1 star"
    stars = int(label[0])
    return stars

In [21]:
df_test["predicted_sentiment_stars"] = df_test["comments"].apply(predict_sentiment_stars)

df_test[["comments", "review_scores_rating", "predicted_sentiment_stars"]].head(20)

,comments,review_scores_rating,predicted_sentiment_stars
0,"excellent stay, i would highly recommend it. a...",4.63,5
1,Britta's apartment in Berlin is in a great are...,4.63,5
2,"Fantastic, large place in good location. Only ...",4.63,5
3,L'appartamento di Britta è molto largo carino ...,4.63,5
4,We went in Berlin for the new year eve. The ap...,4.63,5
5,"Location, location, location! Britta's place w...",4.63,5
6,We were there to find out what life is like in...,4.63,4
7,"Recommended! Nice, informative and easy to dea...",4.63,5
8,Britta's flat is very nice and in a wonderful ...,4.63,4
9,Britta's flat was perfect for our week end in ...,4.63,5
10,I really enjoyed staying at this flat. It was ...,4.63,5
11,I had a great weekend in Berlin with 3 friends...,4.63,5
12,We really enjoyed staying at britta's appartem...,4.63,4
13,Britta's flat is in a great location in a real...,4.63,5
14,Lovely apartment in a great location. My only ...,4.63,4
15,This flat is in one of the nicest areas of Ber...,4.63,5
16,Britta's place is wonderful! We was very comfo...,4.63,5
17,We had a great stay at Britta's apartment-.Ver...,4.63,5
18,We had a great stay in Brittas apartment. We w...,4.63,5
19,"We had a great stay in this vibrant, historic ...",4.63,5

In [22]:
# Differenz zwischen tatsächlicher Bewertung und Modellvorhersage.
df_test["difference"] = df_test["review_scores_rating"] - df_test["predicted_sentiment_stars"]

df_test[["comments", "review_scores_rating", "predicted_sentiment_stars", "difference"]].head(20)

,comments,review_scores_rating,predicted_sentiment_stars,difference
0,"excellent stay, i would highly recommend it. a...",4.63,5,-0.37
1,Britta's apartment in Berlin is in a great are...,4.63,5,-0.37
2,"Fantastic, large place in good location. Only ...",4.63,5,-0.37
3,L'appartamento di Britta è molto largo carino ...,4.63,5,-0.37
4,We went in Berlin for the new year eve. The ap...,4.63,5,-0.37
5,"Location, location, location! Britta's place w...",4.63,5,-0.37
6,We were there to find out what life is like in...,4.63,4,0.63
7,"Recommended! Nice, informative and easy to dea...",4.63,5,-0.37
8,Britta's flat is very nice and in a wonderful ...,4.63,4,0.63
9,Britta's flat was perfect for our week end in ...,4.63,5,-0.37
10,I really enjoyed staying at this flat. It was ...,4.63,5,-0.37
11,I had a great weekend in Berlin with 3 friends...,4.63,5,-0.37
12,We really enjoyed staying at britta's appartem...,4.63,4,0.63
13,Britta's flat is in a great location in a real...,4.63,5,-0.37
14,Lovely apartment in a great location. My only ...,4.63,4,0.63
15,This flat is in one of the nicest areas of Ber...,4.63,5,-0.37
16,Britta's place is wonderful! We was very comfo...,4.63,5,-0.37
17,We had a great stay at Britta's apartment-.Ver...,4.63,5,-0.37
18,We had a great stay in Brittas apartment. We w...,4.63,5,-0.37
19,"We had a great stay in this vibrant, historic ...",4.63,5,-0.37

In [23]:
# Korrelation berechnen
correlation = df_test["review_scores_rating"].corr(df_test["predicted_sentiment_stars"])

print("Korrelation:", correlation)

Korrelation: -9.602805710066561e-16

In [24]:
# Zufällige Stichprobe von 100 Reviews ziehen.
# df.head(100) nimmt nur die ersten 100 Zeilen. Diese können alle zum gleichen Listing gehören,
# wodurch die echten Bewertungen kaum variieren. Eine Zufallsstichprobe ist deshalb sinnvoller.
df_test_random = df.sample(100, random_state=42).copy()

# Für jeden Review-Text wird mit dem vortrainierten Sentiment-Modell
# eine geschätzte Sternebewertung von 1 bis 5 erzeugt.
df_test_random["predicted_sentiment_stars"] = df_test_random["comments"].apply(
    predict_sentiment_stars
)

# Differenz zwischen echter Airbnb-Bewertung und modellbasierter Textbewertung berechnen.
# Positive Werte bedeuten: Die echte Bewertung ist höher als die Stimmung im Text.
# Negative Werte bedeuten: Die Textbewertung fällt höher aus als die echte Airbnb-Bewertung.
df_test_random["difference"] = (
    df_test_random["review_scores_rating"] 
    - df_test_random["predicted_sentiment_stars"]
)

# Ergebnisübersicht anzeigen:
# comments = Bewertungstext
# review_scores_rating = echte Airbnb-Bewertung des Listings
# predicted_sentiment_stars = vom Modell geschätzte Bewertung aus dem Text
# difference = Abweichung zwischen echter Bewertung und Text-Sentiment
df_test_random[
    ["comments", "review_scores_rating", "predicted_sentiment_stars", "difference"]
].head(20)

,comments,review_scores_rating,predicted_sentiment_stars,difference
182615,very nice room. really gorgeous especially th...,4.71,5,-0.29
588295,Great apartment. Close to the city center. Ver...,4.73,5,-0.27
495328,Sehr angenehmer Aufenthalt und vorallem sehr g...,4.90,5,-0.10
465696,Super Zentral und sehr modern! Optisch war das...,4.74,5,-0.26
170944,Matthias's apartment was absolutely stunning a...,5.00,5,0.00
174099,"El apartamento de Robert es inmejorable, siemp...",4.98,5,-0.02
499636,"Most airbnbs feel pretty generic, but this spa...",4.59,4,0.59
361798,Amazing stay in Berlin: the location was very ...,4.92,5,-0.08
8050,"Super tolle Wohnung, perfekt gelegen um Berlin...",4.83,5,-0.17
459343,Perfect stay,4.65,5,-0.35
174512,A great apartment in a cool area with lovely l...,4.78,5,-0.22
512314,Good services and fast response. Clean and tid...,4.71,4,0.71
204234,"She's really nice & friendly person, she alwa...",4.83,5,-0.17
355580,We loved it!! highly recommend if you dont min...,4.63,5,-0.37
419478,Michael hat uns sehr freundlich in Empfang gen...,4.67,5,-0.33
238798,Noch in Umbau,4.40,4,0.40
165937,Wonderful family home in a great location. Ev...,4.97,5,-0.03
341003,"Tolle Lage, mehr als genug Platz für 4 Persone...",4.74,5,-0.26
94872,"Mysigt, rent och allmänt trevligt inrett. Vi t...",4.76,4,0.76
110152,"Muy bonito lugar para descansar, muy buena ubi...",4.47,5,-0.53

In [25]:
# Zusammenhang zwischen echter Airbnb-Bewertung und modellbasierter Textbewertung berechnen
correlation = df_test_random["review_scores_rating"].corr(
    df_test_random["predicted_sentiment_stars"]
)

print("Korrelation zwischen echter Bewertung und Text-Sentiment:", correlation)

Korrelation zwischen echter Bewertung und Text-Sentiment: 0.2887597427854813

In [26]:
# Durchschnittliche Abweichung zwischen echter Bewertung und Text-Sentiment
mean_difference = df_test_random["difference"].mean()

print("Durchschnittliche Abweichung:", mean_difference)

Durchschnittliche Abweichung: 0.05800000000000003

In [27]:
# Häufigkeit der vom Modell vorhergesagten Sternebewertungen
df_test_random["predicted_sentiment_stars"].value_counts().sort_index()

predicted_sentiment_stars
2     2
3     2
4    19
5    77
Name: count, dtype: int64

In [28]:
# Größere zufällige Stichprobe für die finale Analyse
# 100 Reviews waren nur ein Funktionstest.
# Mit 1.000 Reviews werden die Ergebnisse stabiler und aussagekräftiger.

df_sample = df.sample(1000, random_state=42).copy()

print(df_sample.shape)
df_sample[["listing_id", "comments", "review_scores_rating"]].head(10)

(1000, 9)

,listing_id,comments,review_scores_rating
182615,13706588,very nice room. really gorgeous especially th...,4.71
588295,1071626349544551742,Great apartment. Close to the city center. Ver...,4.73
495328,53623941,Sehr angenehmer Aufenthalt und vorallem sehr g...,4.90
465696,49070135,Super Zentral und sehr modern! Optisch war das...,4.74
170944,12319085,Matthias's apartment was absolutely stunning a...,5.00
174099,12967814,"El apartamento de Robert es inmejorable, siemp...",4.98
499636,53988565,"Most airbnbs feel pretty generic, but this spa...",4.59
361798,32016500,Amazing stay in Berlin: the location was very ...,4.92
8050,180440,"Super tolle Wohnung, perfekt gelegen um Berlin...",4.83
459343,46865074,Perfect stay,4.65

In [31]:
# Für jeden Review-Text wird eine Sentiment-Sternebewertung von 1 bis 5 berechnet.

df_sample["predicted_sentiment_stars"] = df_sample["comments"].apply(
    predict_sentiment_stars
)

df_sample[["comments", "review_scores_rating", "predicted_sentiment_stars"]].head(10)

,comments,review_scores_rating,predicted_sentiment_stars
182615,very nice room. really gorgeous especially th...,4.71,5
588295,Great apartment. Close to the city center. Ver...,4.73,5
495328,Sehr angenehmer Aufenthalt und vorallem sehr g...,4.90,5
465696,Super Zentral und sehr modern! Optisch war das...,4.74,5
170944,Matthias's apartment was absolutely stunning a...,5.00,5
174099,"El apartamento de Robert es inmejorable, siemp...",4.98,5
499636,"Most airbnbs feel pretty generic, but this spa...",4.59,4
361798,Amazing stay in Berlin: the location was very ...,4.92,5
8050,"Super tolle Wohnung, perfekt gelegen um Berlin...",4.83,5
459343,Perfect stay,4.65,5

In [32]:
# Differenz zwischen echter Airbnb-Bewertung und modellbasierter Textbewertung berechnen.
# Positive Werte: echte Bewertung ist höher als die Textbewertung.
# Negative Werte: Textbewertung ist höher als die echte Bewertung.

df_sample["difference"] = (
    df_sample["review_scores_rating"] 
    - df_sample["predicted_sentiment_stars"]
)

df_sample[
    ["comments", "review_scores_rating", "predicted_sentiment_stars", "difference"]
].head(20)

,comments,review_scores_rating,predicted_sentiment_stars,difference
182615,very nice room. really gorgeous especially th...,4.71,5,-0.29
588295,Great apartment. Close to the city center. Ver...,4.73,5,-0.27
495328,Sehr angenehmer Aufenthalt und vorallem sehr g...,4.90,5,-0.10
465696,Super Zentral und sehr modern! Optisch war das...,4.74,5,-0.26
170944,Matthias's apartment was absolutely stunning a...,5.00,5,0.00
174099,"El apartamento de Robert es inmejorable, siemp...",4.98,5,-0.02
499636,"Most airbnbs feel pretty generic, but this spa...",4.59,4,0.59
361798,Amazing stay in Berlin: the location was very ...,4.92,5,-0.08
8050,"Super tolle Wohnung, perfekt gelegen um Berlin...",4.83,5,-0.17
459343,Perfect stay,4.65,5,-0.35
174512,A great apartment in a cool area with lovely l...,4.78,5,-0.22
512314,Good services and fast response. Clean and tid...,4.71,4,0.71
204234,"She's really nice & friendly person, she alwa...",4.83,5,-0.17
355580,We loved it!! highly recommend if you dont min...,4.63,5,-0.37
419478,Michael hat uns sehr freundlich in Empfang gen...,4.67,5,-0.33
238798,Noch in Umbau,4.40,4,0.40
165937,Wonderful family home in a great location. Ev...,4.97,5,-0.03
341003,"Tolle Lage, mehr als genug Platz für 4 Persone...",4.74,5,-0.26
94872,"Mysigt, rent och allmänt trevligt inrett. Vi t...",4.76,4,0.76
110152,"Muy bonito lugar para descansar, muy buena ubi...",4.47,5,-0.53

In [33]:
# Korrelation zwischen echter Airbnb-Bewertung und modellbasierter Textbewertung

correlation = df_sample["review_scores_rating"].corr(
    df_sample["predicted_sentiment_stars"]
)

print("Korrelation:", correlation)

Korrelation: 0.19736387871276656

In [34]:
# Durchschnittliche Abweichung zwischen echter Bewertung und Textbewertung

mean_difference = df_sample["difference"].mean()

print("Durchschnittliche Abweichung:", mean_difference)

Durchschnittliche Abweichung: 0.11736000000000002

In [35]:
# Häufigkeiten der vom Modell vorhergesagten Sternebewertungen

df_sample["predicted_sentiment_stars"].value_counts().sort_index()

predicted_sentiment_stars
1      8
2      9
3     29
4    227
5    727
Name: count, dtype: int64

In [42]:
# Zufällige Stichprobe von 50.000 Reviews ziehen
# random_state=42 sorgt dafür, dass die Stichprobe reproduzierbar ist.

df_sample_50000 = df.sample(50000, random_state=42).copy()

print(df_sample_50000.shape)
df_sample_50000[["listing_id", "comments", "review_scores_rating"]].head(10)

(50000, 9)

,listing_id,comments,review_scores_rating
182615,13706588,very nice room. really gorgeous especially th...,4.71
588295,1071626349544551742,Great apartment. Close to the city center. Ver...,4.73
495328,53623941,Sehr angenehmer Aufenthalt und vorallem sehr g...,4.90
465696,49070135,Super Zentral und sehr modern! Optisch war das...,4.74
170944,12319085,Matthias's apartment was absolutely stunning a...,5.00
174099,12967814,"El apartamento de Robert es inmejorable, siemp...",4.98
499636,53988565,"Most airbnbs feel pretty generic, but this spa...",4.59
361798,32016500,Amazing stay in Berlin: the location was very ...,4.92
8050,180440,"Super tolle Wohnung, perfekt gelegen um Berlin...",4.83
459343,46865074,Perfect stay,4.65

In [43]:
# 50.000 blockweise analysieren und speichern.

import os
import pandas as pd

# Einstellungen
chunk_size = 10000
output_file = "sentiment_ergebnisse_50000.csv"

# Falls die Datei schon existiert, abbrechen, damit nichts versehentlich doppelt/überschrieben wird.
if os.path.exists(output_file):
    print(f"Achtung: Die Datei '{output_file}' existiert bereits.")
    print("Bitte lösche oder benenne sie um, bevor du die Analyse neu startest.")
else:
    total_rows = len(df_sample_50000)
    print("Anzahl zu analysierender Reviews:", total_rows)

    for start in range(0, total_rows, chunk_size):
        end = min(start + chunk_size, total_rows)
        print(f"Verarbeite Zeilen {start} bis {end} von {total_rows}")

        # Aktuellen Block kopieren
        df_chunk = df_sample_50000.iloc[start:end].copy()

        # Sentiment-Sterne mit dem vortrainierten Modell berechnen
        df_chunk["predicted_sentiment_stars"] = df_chunk["comments"].apply(
            predict_sentiment_stars
        )

        # Differenz zwischen echter Bewertung und Textbewertung berechnen
        df_chunk["difference"] = (
            df_chunk["review_scores_rating"]
            - df_chunk["predicted_sentiment_stars"]
        )

        # Ersten Block mit Spaltennamen speichern, danach an dieselbe Datei anhängen
        write_header = start == 0

        df_chunk.to_csv(
            output_file,
            mode="a",
            header=write_header,
            index=False
        )

        print(f"Gespeichert: Zeilen {start} bis {end}")

    print("Fertig. Alle 50.000 Ergebnisse wurden gespeichert.")

Anzahl zu analysierender Reviews: 50000
Verarbeite Zeilen 0 bis 10000 von 50000
Gespeichert: Zeilen 0 bis 10000
Verarbeite Zeilen 10000 bis 20000 von 50000
Gespeichert: Zeilen 10000 bis 20000
Verarbeite Zeilen 20000 bis 30000 von 50000
Gespeichert: Zeilen 20000 bis 30000
Verarbeite Zeilen 30000 bis 40000 von 50000
Gespeichert: Zeilen 30000 bis 40000
Verarbeite Zeilen 40000 bis 50000 von 50000
Gespeichert: Zeilen 40000 bis 50000
Fertig. Alle 50.000 Ergebnisse wurden gespeichert.

In [44]:
df_sentiment_50000 = pd.read_csv("sentiment_ergebnisse_50000.csv")

print(df_sentiment_50000.shape)
df_sentiment_50000[
    ["comments", "review_scores_rating", "predicted_sentiment_stars", "difference"]
].head(10)

(50229, 11)

,comments,review_scores_rating,predicted_sentiment_stars,difference
0,very nice room. really gorgeous especially th...,4.71,5.0,-0.29
1,Great apartment. Close to the city center. Ver...,4.73,5.0,-0.27
2,Sehr angenehmer Aufenthalt und vorallem sehr g...,4.90,5.0,-0.10
3,Super Zentral und sehr modern! Optisch war das...,4.74,5.0,-0.26
4,Matthias's apartment was absolutely stunning a...,5.00,5.0,0.00
5,"El apartamento de Robert es inmejorable, siemp...",4.98,5.0,-0.02
6,"Most airbnbs feel pretty generic, but this spa...",4.59,4.0,0.59
7,Amazing stay in Berlin: the location was very ...,4.92,5.0,-0.08
8,"Super tolle Wohnung, perfekt gelegen um Berlin...",4.83,5.0,-0.17
9,Perfect stay,4.65,5.0,-0.35

In [45]:
print(df_sample_50000.shape)

df_sample_50000[
    ["comments", "review_scores_rating", "predicted_sentiment_stars", "difference"]
].head(10)

(50000, 9)

KeyError: "['predicted_sentiment_stars', 'difference'] not in index"

In [46]:
# Spalten der gespeicherten Ergebnisdatei prüfen
print(df_sentiment_50000.shape)
print(df_sentiment_50000.columns.tolist())

(50229, 11)
['listing_id', 'id_x', 'date', 'reviewer_id', 'reviewer_name', 'comments', 'id_y', 'review_scores_rating', 'rating_1_to_5', 'predicted_sentiment_stars', 'difference']

In [47]:
df_sentiment_50000[
    ["comments", "review_scores_rating", "predicted_sentiment_stars", "difference"]
].head(10)

,comments,review_scores_rating,predicted_sentiment_stars,difference
0,very nice room. really gorgeous especially th...,4.71,5.0,-0.29
1,Great apartment. Close to the city center. Ver...,4.73,5.0,-0.27
2,Sehr angenehmer Aufenthalt und vorallem sehr g...,4.90,5.0,-0.10
3,Super Zentral und sehr modern! Optisch war das...,4.74,5.0,-0.26
4,Matthias's apartment was absolutely stunning a...,5.00,5.0,0.00
5,"El apartamento de Robert es inmejorable, siemp...",4.98,5.0,-0.02
6,"Most airbnbs feel pretty generic, but this spa...",4.59,4.0,0.59
7,Amazing stay in Berlin: the location was very ...,4.92,5.0,-0.08
8,"Super tolle Wohnung, perfekt gelegen um Berlin...",4.83,5.0,-0.17
9,Perfect stay,4.65,5.0,-0.35

In [48]:
# Kennzahlen für die 50.000er-Stichprobe berechnen

correlation_50000 = df_sentiment_50000["review_scores_rating"].corr(
    df_sentiment_50000["predicted_sentiment_stars"]
)

mean_difference_50000 = df_sentiment_50000["difference"].mean()

mean_real_rating_50000 = df_sentiment_50000["review_scores_rating"].mean()

mean_sentiment_rating_50000 = df_sentiment_50000["predicted_sentiment_stars"].mean()

print("Anzahl analysierter Reviews:", len(df_sentiment_50000))
print("Korrelation:", correlation_50000)
print("Durchschnitt echte Airbnb-Bewertung:", mean_real_rating_50000)
print("Durchschnitt modellbasierte Textbewertung:", mean_sentiment_rating_50000)
print("Durchschnittliche Abweichung:", mean_difference_50000)

Anzahl analysierter Reviews: 50229
Korrelation: 0.23375930329276506
Durchschnitt echte Airbnb-Bewertung: 4.767047836629993
Durchschnitt modellbasierte Textbewertung: 4.639511813864005
Durchschnittliche Abweichung: 0.1275360227659873

In [49]:
# Verteilung der vorhergesagten Sentiment-Sterne

df_sentiment_50000["predicted_sentiment_stars"].value_counts().sort_index()

predicted_sentiment_stars
1.0      328
2.0      600
3.0     1744
4.0    11388
5.0    35839
Name: count, dtype: int64

In [50]:
df_sentiment_50000_clean = df_sentiment_50000.dropna(
    subset=["review_scores_rating", "predicted_sentiment_stars", "difference"]
)

print(df_sentiment_50000_clean.shape)

(49899, 11)

In [51]:
df_sentiment_50000_clean.to_excel("sentiment_ergebnisse_49899_clean.xlsx", index=False)

In [52]:
df_sentiment_50000_clean.to_csv("sentiment_ergebnisse_49899_clean.csv", index=False)